server:
  port: 2003

spring:
  application:
    name: seata-account-service
  cloud:
    nacos:
      discovery:
        server-addr: 172.16.40.101:8848
    alibaba:
      seata:
        #自定义事务组名称需要与seata-server中的对应
        tx-service-group: fsp_tx_default
  datasource:
    #driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://172.16.40.102:3306/seata_account?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: graps
    password: 123456

feign:
  hystrix:
    enabled: false
logging:
  level:
    io:
      seata: info

mybatis:
  #mapper-locations: classpath:/*.mapper
  mapperLocations: classpath:mapper/*.xml

