server:
  port: 3344

spring:
  application:
    name:  cloud-config-center #注册进Eureka服务器的微服务名
  cloud:
    config:
      server:
        git:
          #uri: git@github.com:WangZhiDian/springcloud-config.git #GitHub上面的git仓库名字
          #uri: https://github.com/WangZhiDian/springcloud-config.git
          #username: wang_zhidian@163.com
          #password: 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
          uri: https://gitee.com/wangzhidian/springcloud-config.git
          username: wang_zhidian@163.com
          password: neuqwd1234


          ####搜索目录
          search-paths:
            - springcloud-config
      ####读取分支
      label: master

  #rabbitmq相关配置<--------------------------
  rabbitmq:
    host: 172.16.40.101
    port: 5672
    username: wangzhidian
    password: neuqwangdian

##rabbitmq相关配置,暴露bus刷新配置的端点<--------------------------
management:
  endpoints: #暴露bus刷新配置的端点
    web:
      exposure:
        include: 'bus-refresh'

#服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
