
server:
  port: 7002


eureka:
  instance:
    #hostname: localhost  #Eureka 服务端的实例名称
    hostname: eureka7002.com  #Eureka 服务端的实例名称
  client:
    # 是否启动时注册到eureka注册中心，这里本身是注册中心，就不注册了
    register-with-eureka: false
    #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    fetch-registry: false
    service-url:
      #设置与Eureka server交互的地址查询服务和注册服务都需要依赖这个地址,如果集群，就填写下方所示,和其他的相呼应。
      defaultZone: http://eureka7001.com:7001/eureka/
      #设置与Eureka server交互的地址查询服务和注册服务都需要依赖这个地址,如果单机，就填写下方所示。
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
